from __future__ import annotations

import uuid
from collections import defaultdict
from datetime import datetime

from src.engine.order.models import Order, OrderSide, OrderStatus, OrderType, Trade


class OrderBook:
    """Order book and matching engine.

    Implements price-time priority matching for LIMIT and MARKET orders.
    """

    def __init__(self) -> None:
        # symbol -> list of active orders (both bids and asks)
        self._orders: dict[str, list[Order]] = defaultdict(list)
        # order_id -> Order for fast lookup
        self._order_index: dict[str, Order] = {}

    def add_order(self, order: Order) -> list[Trade]:
        """Add an order to the book and attempt to match it.

        Returns a list of trades generated by the match.
        """
        if order.status == OrderStatus.CANCELLED:
            return []

        # Validate market orders have a price for matching purposes.
        if order.type == OrderType.MARKET and order.price is None:
            # Market orders will match against the best available price.
            pass

        # Initialize order status
        if order.status == OrderStatus.PENDING:
            order.status = OrderStatus.OPEN

        # Store order
        self._orders[order.symbol].append(order)
        self._order_index[order.id] = order

        # Attempt to match
        trades = self._match(order)

        # If not fully filled and it's a limit order, keep it open
        if (
            not order.is_filled()
            and order.type == OrderType.LIMIT
            and order.status not in (OrderStatus.PARTIALLY_FILLED, OrderStatus.OPEN)
        ):
            order.status = OrderStatus.OPEN

        # If market order couldn't fully fill, mark remaining as cancelled/rejected
        if not order.is_filled() and order.type == OrderType.MARKET:
            if order.filled_quantity > 0:
                order.status = OrderStatus.PARTIALLY_FILLED
            else:
                order.status = OrderStatus.REJECTED

        return trades

    def cancel_order(self, order_id: str) -> bool:
        """Cancel an order by ID. Returns True if cancelled, False if not found or already filled."""
        order = self._order_index.get(order_id)
        if order is None:
            return False
        if not order.is_active():
            return False
        order.status = OrderStatus.CANCELLED
        return True

    def get_orders(self, symbol: str | None = None) -> list[Order]:
        """Get all orders, optionally filtered by symbol."""
        if symbol is not None:
            return list(self._orders.get(symbol, []))
        result: list[Order] = []
        for orders in self._orders.values():
            result.extend(orders)
        return result

    def get_bids(self, symbol: str) -> list[Order]:
        """Get active buy orders for a symbol, sorted by price desc then time asc."""
        orders = [
            o for o in self._orders.get(symbol, [])
            if o.side == OrderSide.BUY and o.is_active()
        ]
        return sorted(orders, key=lambda o: (-(o.price or 0), o.created_at))

    def get_asks(self, symbol: str) -> list[Order]:
        """Get active sell orders for a symbol, sorted by price asc then time asc."""
        orders = [
            o for o in self._orders.get(symbol, [])
            if o.side == OrderSide.SELL and o.is_active()
        ]
        return sorted(orders, key=lambda o: (o.price or float("inf"), o.created_at))

    def _match(self, incoming: Order) -> list[Trade]:
        """Match an incoming order against the opposite side of the book."""
        trades: list[Trade] = []

        if incoming.side == OrderSide.BUY:
            candidates = self.get_asks(incoming.symbol)
        else:
            candidates = self.get_bids(incoming.symbol)

        for candidate in candidates:
            if not candidate.is_active():
                continue
            if incoming.is_filled():
                break

            if not self._can_match(incoming, candidate):
                continue

            trade = self._execute_trade(incoming, candidate)
            trades.append(trade)

        return trades

    def _can_match(self, incoming: Order, candidate: Order) -> bool:
        """Check if two orders can match based on price."""
        # Determine the trade price
        incoming_price = incoming.price
        candidate_price = candidate.price

        if incoming.type == OrderType.MARKET:
            # Market order matches at candidate's price
            return candidate_price is not None

        if candidate.type == OrderType.MARKET:
            # Limit incoming matches market candidate
            return incoming_price is not None

        # Both are limit orders
        if incoming_price is None or candidate_price is None:
            return False

        if incoming.side == OrderSide.BUY:
            return incoming_price >= candidate_price
        else:
            return incoming_price <= candidate_price

    def _execute_trade(self, incoming: Order, candidate: Order) -> Trade:
        """Execute a trade between two orders and update their states."""
        trade_quantity = min(incoming.remaining_quantity(), candidate.remaining_quantity())

        # Determine trade price
        if incoming.type == OrderType.MARKET and candidate.type == OrderType.MARKET:
            # Both market: use a reference price if available, otherwise 0 (shouldn't happen in practice)
            trade_price = candidate.price or incoming.price or 0.0
        elif incoming.type == OrderType.MARKET:
            trade_price = candidate.price or 0.0
        elif candidate.type == OrderType.MARKET:
            trade_price = incoming.price or 0.0
        else:
            # Both limit: price is the candidate's price (price-time priority)
            trade_price = candidate.price or incoming.price or 0.0

        # Update incoming order
        incoming.filled_quantity += trade_quantity
        incoming.average_price = (
            (incoming.average_price * (incoming.filled_quantity - trade_quantity))
            + (trade_price * trade_quantity)
        ) / incoming.filled_quantity if incoming.filled_quantity > 0 else 0.0

        if incoming.is_filled():
            incoming.status = OrderStatus.FILLED
        else:
            incoming.status = OrderStatus.PARTIALLY_FILLED

        # Update candidate order
        candidate.filled_quantity += trade_quantity
        candidate.average_price = (
            (candidate.average_price * (candidate.filled_quantity - trade_quantity))
            + (trade_price * trade_quantity)
        ) / candidate.filled_quantity if candidate.filled_quantity > 0 else 0.0

        if candidate.is_filled():
            candidate.status = OrderStatus.FILLED
        else:
            candidate.status = OrderStatus.PARTIALLY_FILLED

        buy_id = incoming.id if incoming.side == OrderSide.BUY else candidate.id
        sell_id = candidate.id if candidate.side == OrderSide.SELL else incoming.id
        trade = Trade(
            id=str(uuid.uuid4()),
            buy_order_id=buy_id,
            sell_order_id=sell_id,
            symbol=incoming.symbol,
            quantity=trade_quantity,
            price=trade_price,
            timestamp=datetime.utcnow(),
            fee=0.0,
        )

        return trade
